language: python
python: "3.5"
install: pip install "virtualenv<14.0.0"
script: python setup.py test
env:
  # To generate (update) the env list run
  # $ tox -l | sort | xargs -I ITEM echo "  - TOXENV="ITEM
  - TOXENV=flake8-py26
  - TOXENV=flake8-py27
  - TOXENV=flake8-py32
  - TOXENV=flake8-py33
  - TOXENV=flake8-py34
  - TOXENV=flake8-py35
  - TOXENV=py26-django14
  - TOXENV=py26-django15
  - TOXENV=py26-django16
  - TOXENV=py27-django14
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py32-django15
  - TOXENV=py32-django16
  - TOXENV=py32-django17
  - TOXENV=py32-django18
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=pylint-py27-django19
  - TOXENV=pylint-py35-django19
